// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKQ7Rr3NCvLvHIpo9Slf8uqeAufAkkv8Y',
    appId: '1:115484151143:web:9f9eeffc063b5266b9b3c2',
    messagingSenderId: '115484151143',
    projectId: 'xpt-prototype',
    authDomain: 'xpt-prototype.firebaseapp.com',
    storageBucket: 'xpt-prototype.appspot.com',
    measurementId: 'G-2XJKXFKCDQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCelk3HTg7lqQxZln5QpZnuBz0Cfv56O0g',
    appId: '1:115484151143:android:b3f924ad0c4e48fab9b3c2',
    messagingSenderId: '115484151143',
    projectId: 'xpt-prototype',
    storageBucket: 'xpt-prototype.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv75pXV0Ye9qS3aDKCqGP8FEzDuB_3gHw',
    appId: '1:115484151143:ios:f0acf8dbc0617219b9b3c2',
    messagingSenderId: '115484151143',
    projectId: 'xpt-prototype',
    storageBucket: 'xpt-prototype.appspot.com',
    iosClientId: '115484151143-cipvodk9uskjhgns4m48hof1j6s7hc2t.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv75pXV0Ye9qS3aDKCqGP8FEzDuB_3gHw',
    appId: '1:115484151143:ios:f0acf8dbc0617219b9b3c2',
    messagingSenderId: '115484151143',
    projectId: 'xpt-prototype',
    storageBucket: 'xpt-prototype.appspot.com',
    iosClientId: '115484151143-cipvodk9uskjhgns4m48hof1j6s7hc2t.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
